server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo-springboot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: yangfei2000
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: com/feoyang/infrastructure/**/*.xml

